#+TITLE: Math Symbol Classifier
#+AUTHOR: Reid Chen, Jijie Zhang
#+EMAIL: reid@cs.wisc.edu, jzhang998@wisc.edu
#+OPTIONS: toc:nil email:1 nums:nil
#+LATEX_HEADER: \bibliographystyle{acm}
* Why are we doing this project?
Many students use electronic devices for note-taking because it is convenient and accessible.  As a college student, many of our courses involve mathematical symbols and equations. Taking notes on an iPad gives great flexibility since it is easier for me to organize and search through my notes. However, when we searched our notes, one problem is that although we are able to search through the words we wrote, formulas and other mathematical symbols cannot be recognized by my note taking software or it is simply misrecognized. Therefore, our group would like to proposal a solution to this problem. We want to design a handwriting recognition system that not only recognizes text, but also mathematical formulas and symbols.
* What will we be doing?
Handwriting recognitions are one of the first problems that neural networks are trying to solve. LeNet5 cite:lecun1998gradient is a classic CNN model that has a purpose of recognizing handwritten numbers and has a pioneering, good result. Therefore, we are planning to design a CNN that recognizes 3 types of handwritten: 1. English 2. Numbers 3. Mathematical symbols. Since our focus is mathematical symbols, we want our model to be able to map the handwritten mathematical symbols into their corresponding LaTeX representation.
* How will we be doing it?
  cite:lecun1998gradient,zanibbi2012recognition,balci2017handwritten  provides some insights about recognizing numbers, mathematical symbols, and English words. Therefore, rather than building everything from scratch, we are planning to adopt the idea of transfer learning to take the advantage of some existing models and use them to extract features from input data (images). We plan to use MNIST cite:lecun-mnisthandwrittendigit-2010, IAM handwriting Database cite:journals/ijdar/MartiB02, together with CROHME 2019 cite:conf/icdar/MahdaviZMVG19 dataset to train, test, and validate our model. To better test and demonstrate our model, we are planning to design an iPad app which allows users to write the input data using Apple Pencil and recognizes it using the model we have trained.
* Who will be doing it?
Our group has two members, Reid Chen and Jijie Zhang. Reid will be responsible for concept applying, modeling and the demo app designing. Jijie will be responsible for data collection and testing. 
* How long will it take?
The project is estimated to take five weeks. First week is for summarizing needed concepts like CNN and building model structures. Second week consists of data collection, data filtering and selection. Week three and week four will be focused on finishing model construction, training models with data and integrating them into an App (Reid has experience with developing App for Apple Devices, so this App developing process will not take a long time). In Week 5, we will test and tune our program. 

bibliography:references.bib
